export const REQUEST_ARTIST_DETAILS = 'REQUEST_ARTIST_DETAILS';
export const RECEIVE_ARTIST_DETAILS = 'RECEIVE_ARTIST_DETAILS';
export const REQUEST_ARTIST_ALBUMS = 'REQUEST_ARTIST_ALBUMS';
export const RECEIVE_ARTIST_ALBUMS = 'RECEIVE_ARTIST_ALBUMS';
export const REQUEST_ALBUM_DETAILS = 'REQUEST_ALBUM_DETAILS';
export const RECEIVE_ALBUM_DETAILS = 'RECEIVE_ALBUM_DETAILS';